# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-24 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bima_back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Username')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('filter', models.TextField(verbose_name='Filter')),
            ],
            options={
                'verbose_name_plural': 'Photo filters',
                'verbose_name': 'Photo filter',
                'ordering': ('username',),
            },
        ),
    ]
