# Generated by Django 3.2 on 2022-02-22 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bima_back', '0002_photofilter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mychunkedupload',
            options={'verbose_name': 'My chunked upload', 'verbose_name_plural': 'My chunked uploads'},
        ),
        migrations.AlterField(
            model_name='damuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='damuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='mychunkedupload',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='my_chunked_uploads', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
